const district = [
{value:'all',label:'All'},
{value:'Ahmednagar',label:'Ahmednagar'},
{value:'Akola',label:'Akola'},
{value:'Amravati',label:'Amravati'},
{value:'Aurangabad',label:'Aurangabad'},
{value:'Beed',label:'Beed'},
{value:'Bhandara',label:'Bhandara'},
{value:'Buldhana',label:'Buldhana'},
{value:'Chandrapur',label:'Chandrapur'},
{value:'Dhule',label:'Dhule'},
{value:'Jalgaon',label:'Jalgaon'},
{value:'Jalna',label:'Jalna'},
{value:'Kolhapur',label:'Kolhapur'},
{value:'Latur',label:'Latur'},
{value:'Mumbai City',label:'Mumbai City'},
{value:'Mumbai Suburban',label:'Mumbai Suburban'},
{value:'Nagpur',label:'Nagpur'},
{value:'Nanded',label:'Nanded'},
{value:'Nandurbar',label:'Nandurbar'},
{value:'Nashik',label:'Nashik'},
{value:'Osmanabad',label:'Osmanabad'},
{value:'Palghar',label:'Palghar'},
{value:'Parbhani',label:'Parbhani'},
{value:'Pune',label:'Pune'},
{value:'Raigad',label:'Raigad'},
{value:'Ratnagiri',label:'Ratnagiri'},
{value:'Sangli',label:'Sangli'},
{value:'Satara',label:'Satara'},
{value:'Sindhudurg',label:'Sindhudurg'},
{value:'Solapur',label:'Solapur'},
{value:'Thane',label:'Thane'},
{value:'Wardha',label:'Wardha'},
{value:'Washim',label:'Washim'},
{value:'Yavatmal',label:'Yavatmal'},
]

export default district
